const DEMO_DATA = [
  {
    id: 1,
    username: "tin",
    first_name: "Tin",
    last_name: "Nguyen",
    email: "tin@example.com",
    avatar: null,
  },
  {
    id: 2,
    username: "nva",
    first_name: "Nguyễn",
    last_name: "A",
    email: "nva@mail.com",
    avatar: null,
  },
  {
    id: 3,
    username: "nvb",
    first_name: "Nguyễn",
    last_name: "Văn B",
    email: "nvb@mail.com",
    avatar: null,
  },
  {
    id: 4,
    username: "nvc",
    first_name: "Nguyễn Văn",
    last_name: "C",
    email: "nvc@gmail.com",
    avatar: null,
  },
  {
    id: 5,
    username: "nve",
    first_name: "Nguyễn Văn",
    last_name: "E",
    email: "nve@gmail.com",
    avatar: null,
  },
  {
    id: 6,
    username: "nvf",
    first_name: "Nguyễn Văn",
    last_name: "F",
    email: "nvf@gmail.com",
    avatar: null,
  },
  {
    id: 7,
    username: "nvg",
    first_name: "Nguyen Van",
    last_name: "G",
    email: "nvg@gmail.com",
    avatar: null,
  },
  {
    id: 8,
    username: "",
    first_name: "",
    last_name: "",
    email: "root@root.com",
    avatar: null,
  },
  {
    id: 12,
    username: "quynh.nhu.pham.2505@gmail.com",
    first_name: "",
    last_name: "",
    email: "quynh.nhu.pham.2505@gmail.com",
    avatar: null,
  },
  {
    id: 28,
    username: "ajkvbnasjisv",
    first_name: "Van-Loc",
    last_name: "Nguyen",
    email: "ajkvbnasjisv@gmail.com",
    avatar: null,
  },
  {
    id: 9,
    username: "loc.nguyen.test1",
    first_name: "Loc",
    last_name: "Nguyen",
    email: "loc.nguyen.test1@gmail.com",
    avatar: null,
  },
  {
    id: 13,
    username: "quynh.nhu.test@gmail.com",
    first_name: "",
    last_name: "",
    email: "quynh.nhu.test@gmail.com",
    avatar: null,
  },
  {
    id: 14,
    username: "lmao",
    first_name: "Tin",
    last_name: "Nguyen",
    email: "tin@gmail.com",
    avatar: null,
  },
  {
    id: 15,
    username: "test",
    first_name: "test",
    last_name: "test",
    email: "test@gmail.com",
    avatar: null,
  },
  {
    id: 16,
    username: "nvt",
    first_name: "Nguyễn Văn",
    last_name: "Tùng",
    email: "nvt@gmail.com",
    avatar: null,
  },
  {
    id: 17,
    username: "ntm",
    first_name: "Nguyễn thị",
    last_name: "Mỹ",
    email: "mtm@gmail.com",
    avatar: null,
  },
  {
    id: 18,
    username: "testtui",
    first_name: "Test",
    last_name: "Tui",
    email: "testtui@gmail.com",
    avatar: null,
  },
  {
    id: 19,
    username: "ntt",
    first_name: "Nguyễn Thị",
    last_name: "Test",
    email: "ntt@gmail.com",
    avatar: null,
  },
  {
    id: 21,
    username: "admin@admin.com",
    first_name: "",
    last_name: "",
    email: "admin@admin.com",
    avatar: null,
  },
  {
    id: 22,
    username: "tin@admin.com",
    first_name: "",
    last_name: "",
    email: "tin@admin.com",
    avatar: null,
  },
  {
    id: 23,
    username: "asd",
    first_name: "Tin",
    last_name: "Nguyen",
    email: "asd@example.com",
    avatar: null,
  },
  {
    id: 25,
    username: "vanloc1808",
    first_name: "Van-Loc",
    last_name: "Nguyen",
    email: "vanloc1808@gmail.com",
    avatar: null,
  },
  {
    id: 26,
    username: "vanloc1808123",
    first_name: "Van-Loc",
    last_name: "Nguyen",
    email: "vanloc1808123456@gmail.com",
    avatar: null,
  },
  {
    id: 27,
    username: "ngtest",
    first_name: "Nguyễn",
    last_name: "Test",
    email: "ngtest@mail.com",
    avatar: null,
  },
  {
    id: 31,
    username: "lord",
    first_name: "Bao-Tin",
    last_name: "Nguyen",
    email: "lord@gmail.com",
    avatar: null,
  },
  {
    id: 29,
    username: "tuikhongphainhu",
    first_name: "Nhu",
    last_name: "Pham",
    email: "quynh.nhu.test2@gmail.com",
    avatar: null,
  },
  {
    id: 24,
    username: "tuilanhu",
    first_name: "Nhu",
    last_name: "Pham",
    email: "quynh.nhu.test1@gmail.com",
    avatar:
      "/media/users/user/24/27517f05-1b6d-4ebb-a257-9bb03f7e9caf/drl.jpeg",
  },
  {
    id: 32,
    username: "lordvcl",
    first_name: "Bao-Tin",
    last_name: "Nguyen",
    email: "lordvcl@gmail.com",
    avatar: null,
  },
  {
    id: 30,
    username: "tuikhongphainhudau",
    first_name: "Nhu",
    last_name: "Pham",
    email: "phamthiquynhnhu.test@gmail.com",
    avatar: "/media/users/user/30/e47329a6-1cb1-4632-b1b0-ed07df618f5c/ngu.png",
  },
];

export { DEMO_DATA };
