const DEMO_DATA = [
  {
    id: 0,
    sender: 0,
    receiver: 0,
    group: 0,
    time: "2023-12-28T13:05:26.564Z",
    content: "Nội dung hôm nay",
    media: "string",
    avatar: null,
    conversation_name: "Nhóm 1",
  },
  {
    id: 1,
    sender: 0,
    receiver: 0,
    group: 0,
    time: "2023-12-28T13:05:26.564Z",
    content: "Nội dung hôm nay",
    media: "string",
    avatar: null,
    conversation_name: "Nhóm 2",
  },
  {
    id: 2,
    sender: 0,
    receiver: 0,
    group: 0,
    time: "2023-12-28T13:05:26.564Z",
    content: "Nội dung hôm nay",
    media: "string",
    avatar: null,
    conversation_name: "Nhóm 3",
  },
  {
    id: 3,
    sender: 0,
    receiver: 0,
    group: 0,
    time: "2023-12-28T13:05:26.564Z",
    content: "Nội dung hôm nay gồm các thông tin abc def",
    media: "string",
    avatar: null,
    conversation_name: "Nhóm 4",
  },
  {
    id: 4,
    sender: 0,
    receiver: 0,
    group: 0,
    time: "2023-12-28T13:05:26.564Z",
    content: "Nội dung hôm nay gửi đến các bạn trẻ ở hồ chí minh là như này nè",
    media: "string",
    avatar: null,
    conversation_name: "Nhóm các bạn đồng hương Hồ Chí Minh",
  },
];

export { DEMO_DATA };
